name: Deploy to Amazon S3
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://awsdevops.click --delete

      - name: Collect status
        id: collect_status
        run: |
          echo "DEPLOY_STATUS=$([[ '${{ steps.apply.outcome }}' == 'upload: public/index.html to s3://awsdevops.click/index.html' ]] && echo '✅ Success' || echo '❌ Failed')" >> $GITHUB_ENV

      - name: Send Telegram Notification
        if: always()
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *GitHab Actions CI Results*:
            *Step name*: Deploy static site to S3 bucket
            *Status*: ${{ env.DEPLOY_STATUS }}
